# Generated by Django 3.1.6 on 2021-02-09 04:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_auto_20210209_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 4, 28, 39, 186062, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 4, 28, 39, 185062, tzinfo=utc)),
        ),
    ]
