# Generated by Django 3.1.5 on 2021-02-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_nickname', models.CharField(max_length=20)),
                ('user_attend', models.IntegerField(default=0)),
            ],
        ),
    ]
