# Generated by Django 3.1.5 on 2021-02-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='user_absent',
            field=models.IntegerField(default=0),
        ),
    ]
