# Generated by Django 3.1.5 on 2021-02-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendApp', '0002_studentuser_user_absent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20)),
                ('subject_date', models.DateTimeField(verbose_name='date published')),
                ('subject_spec', models.CharField(max_length=50)),
                ('subject_tutor', models.CharField(max_length=5)),
                ('subject_comp', models.IntegerField(default=100)),
            ],
        ),
    ]
