# Generated by Django 3.1.5 on 2021-02-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendApp', '0003_totalcurriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalcurriculum',
            name='subject_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
