# Generated by Django 3.1.5 on 2021-02-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendApp', '0005_specdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
    ]
