# Generated by Django 3.1.6 on 2021-02-09 04:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0003_auto_20210209_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 4, 28, 39, 190064, tzinfo=utc)),
        ),
    ]
