# Generated by Django 3.1.6 on 2021-02-16 00:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello_app', '0010_auto_20210209_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAnswer',
        ),
        migrations.DeleteModel(
            name='UserRegister',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 0, 19, 14, 859321, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
