# Generated by Django 3.1.6 on 2021-02-16 04:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0011_auto_20210216_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 4, 20, 18, 161577, tzinfo=utc)),
        ),
    ]
