# Generated by Django 3.1.5 on 2021-02-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegister',
            new_name='UserRegister2',
        ),
    ]
