# Generated by Django 3.1.6 on 2021-02-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuApp', '0003_auto_20210209_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuprofile',
            name='user_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
