# Generated by Django 3.1.6 on 2021-02-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuApp', '0004_stuprofile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuprofile',
            name='user_email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='stuprofile',
            name='user_pwd',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
