# Generated by Django 3.1.6 on 2021-02-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuApp', '0006_remove_stuprofile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuprofile',
            name='calendar_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stuprofile',
            name='calendar_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stuprofile',
            name='calendar_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stuprofile',
            name='user_absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stuprofile',
            name='user_attend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stuprofile',
            name='user_late',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stuprofile',
            name='user_outing',
            field=models.IntegerField(default=0),
        ),
    ]
